"""init

Revision ID: 012b9fae8698
Revises: 6087562d304d
Create Date: 2024-05-16 19:18:11.428684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012b9fae8698'
down_revision: Union[str, None] = '6087562d304d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_product', 'wb_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_product', sa.Column('wb_price', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
