"""init

Revision ID: 094e55beb5e7
Revises: 8d087c818d60
Create Date: 2024-04-02 12:15:57.929608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094e55beb5e7'
down_revision: Union[str, None] = '8d087c818d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('useragent', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('login_date', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('telegram', sa.String(), nullable=False))
    op.drop_column('user', 'inn')
    op.drop_column('user', 'url')
    op.drop_column('user', 'fathername')
    op.drop_column('user', 'refer_id')
    op.drop_column('user', 'org')
    op.drop_column('user', 'surname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('org', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('refer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('fathername', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('inn', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'telegram')
    op.drop_column('user', 'email')
    op.drop_table('user_status_history')
    op.drop_table('user_status')
    op.drop_table('user_session')
    # ### end Alembic commands ###
