"""init

Revision ID: 3faded85a413
Revises: ed864b36bf37
Create Date: 2024-05-22 13:25:21.180281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3faded85a413'
down_revision: Union[str, None] = 'ed864b36bf37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_review', sa.Column('with_size', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_review', 'with_size')
    # ### end Alembic commands ###
