"""init

Revision ID: 6087562d304d
Revises: c7a99d3dcdb8
Create Date: 2024-05-16 18:42:41.788670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6087562d304d'
down_revision: Union[str, None] = 'c7a99d3dcdb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE products_product ALTER COLUMN wb_price TYPE INTEGER USING wb_price::integer;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_product', sa.Column('unicode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products_product', type_='foreignkey')
    op.drop_column('products_product', 'media_id')
    # ### end Alembic commands ###
