"""init

Revision ID: 619fdc8e848e
Revises: 664b5c69d3c2
Create Date: 2024-04-15 12:24:52.987276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619fdc8e848e'
down_revision: Union[str, None] = '664b5c69d3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balance_bill', 'media_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('balance_history', 'description',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('balance_source', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balance_source', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('balance_history', 'description',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('balance_bill', 'media_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
