"""init

Revision ID: 69843aa05236
Revises: 619fdc8e848e
Create Date: 2024-04-15 12:31:17.492281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69843aa05236'
down_revision: Union[str, None] = '619fdc8e848e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_bill_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('balance_bill', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'balance_bill', 'storage', ['media_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'balance_bill', 'organization', ['org_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'balance_bill', 'balance_source', ['source_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'balance_bill', 'balance_bill_status', ['status_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'balance_history', 'organization', ['org_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'balance_history', 'balance_action', ['action_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balance_history', type_='foreignkey')
    op.drop_constraint(None, 'balance_history', type_='foreignkey')
    op.drop_constraint(None, 'balance_bill', type_='foreignkey')
    op.drop_constraint(None, 'balance_bill', type_='foreignkey')
    op.drop_constraint(None, 'balance_bill', type_='foreignkey')
    op.drop_constraint(None, 'balance_bill', type_='foreignkey')
    op.drop_column('balance_bill', 'status_id')
    op.drop_table('balance_bill_status')
    # ### end Alembic commands ###
