"""init

Revision ID: 8d087c818d60
Revises: 
Create Date: 2024-03-28 17:15:45.477586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d087c818d60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('fathername', sa.String(), nullable=True),
    sa.Column('org', sa.String(), nullable=False),
    sa.Column('inn', sa.String(), nullable=False),
    sa.Column('telnum', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('refer_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
