"""init

Revision ID: a10e316e50a3
Revises: b4c4ec9d8e2b
Create Date: 2024-05-24 15:03:25.379268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10e316e50a3'
down_revision: Union[str, None] = 'b4c4ec9d8e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products_product_size', 'wb_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products_product_size', 'wb_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
