"""init

Revision ID: a35907563288
Revises: e45077f1ef19
Create Date: 2024-04-09 12:54:09.297641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a35907563288'
down_revision: Union[str, None] = 'e45077f1ef19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_invitation', 'expires',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('organization_invitation', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization_invitation', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('organization_invitation', 'expires',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
