"""init

Revision ID: a7818d095307
Revises: 012b9fae8698
Create Date: 2024-05-16 19:18:52.614685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7818d095307'
down_revision: Union[str, None] = '012b9fae8698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_product', sa.Column('wb_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_product', 'wb_price')
    # ### end Alembic commands ###
