"""init

Revision ID: b4c4ec9d8e2b
Revises: 3faded85a413
Create Date: 2024-05-23 18:43:42.929185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c4ec9d8e2b'
down_revision: Union[str, None] = '3faded85a413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_review_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_product_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wb_size_name', sa.String(), nullable=True),
    sa.Column('wb_size_origName', sa.String(), nullable=True),
    sa.Column('wb_size_optionId', sa.String(), nullable=False),
    sa.Column('wb_in_stock', sa.Boolean(), nullable=False),
    sa.Column('wb_price', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products_product.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('products_product', 'wb_sys_size')
    op.drop_column('products_product', 'wb_price')
    op.drop_column('products_product', 'wb_size')
    op.add_column('products_review', sa.Column('size_id', sa.Integer(), nullable=True))
    op.add_column('products_review', sa.Column('match_id', sa.Integer(), nullable=True))
    op.alter_column('products_review', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'products_review', 'products_product_size', ['size_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'products_review', 'products_review_match', ['match_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('products_review', 'with_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_review', sa.Column('with_size', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products_review', type_='foreignkey')
    op.drop_constraint(None, 'products_review', type_='foreignkey')
    op.alter_column('products_review', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products_review', 'match_id')
    op.drop_column('products_review', 'size_id')
    op.add_column('products_product', sa.Column('wb_size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products_product', sa.Column('wb_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products_product', sa.Column('wb_sys_size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('products_product_size')
    op.drop_table('products_review_match')
    # ### end Alembic commands ###
