"""init

Revision ID: c407c69f84a4
Revises: a10e316e50a3
Create Date: 2024-05-24 15:25:13.023231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c407c69f84a4'
down_revision: Union[str, None] = 'a10e316e50a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_product_size', 'wb_size_optionId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_product_size', sa.Column('wb_size_optionId', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
