"""init

Revision ID: c7a99d3dcdb8
Revises: 8cc0be60ac73
Create Date: 2024-04-16 14:26:15.391866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a99d3dcdb8'
down_revision: Union[str, None] = '8cc0be60ac73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('unicode', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('wb_article', sa.String(), nullable=False),
    sa.Column('wb_title', sa.String(), nullable=False),
    sa.Column('wb_size', sa.String(), nullable=True),
    sa.Column('wb_price', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('balance_bill_source_id_fkey', 'balance_bill', type_='foreignkey')
    op.create_foreign_key(None, 'balance_bill', 'balance_source', ['source_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balance_bill', type_='foreignkey')
    op.create_foreign_key('balance_bill_source_id_fkey', 'balance_bill', 'balance_source', ['source_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_table('products_product')
    # ### end Alembic commands ###
