"""init

Revision ID: ca5e5cef58f6
Revises: 8d2ac7353fdd
Create Date: 2024-05-20 16:56:33.688901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5e5cef58f6'
down_revision: Union[str, None] = '8d2ac7353fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_product', sa.Column('wb_sys_size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_product', 'wb_sys_size')
    # ### end Alembic commands ###
