"""init

Revision ID: cfce1e78c543
Revises: 69843aa05236
Create Date: 2024-04-15 12:34:27.418863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfce1e78c543'
down_revision: Union[str, None] = '69843aa05236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_bill', sa.Column('date', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    op.add_column('balance_history', sa.Column('date', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance_history', 'date')
    op.drop_column('balance_bill', 'date')
    # ### end Alembic commands ###
