"""init

Revision ID: d55239d81327
Revises: 28c8a11df02a
Create Date: 2024-04-04 14:43:11.829452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55239d81327'
down_revision: Union[str, None] = '28c8a11df02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_session', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_status_history', 'user_status', ['status_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_status_history', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_status_history', type_='foreignkey')
    op.drop_constraint(None, 'user_status_history', type_='foreignkey')
    op.drop_constraint(None, 'user_session', type_='foreignkey')
    # ### end Alembic commands ###
