"""init

Revision ID: e45077f1ef19
Revises: 65d3f74251e5
Create Date: 2024-04-09 12:51:20.751255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e45077f1ef19'
down_revision: Union[str, None] = '65d3f74251e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_invitation', sa.Column('amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_invitation', 'amount')
    # ### end Alembic commands ###
