cookies_token_key = 'AT'
cookies_admin_token_key = 'AAT'

string_500 = 'Произошла ошибка при выполнении операции. Обновите страницу и повторите попытку'
string_200 = 'Операция успешно выполнена'
string_403 = 'Доступ запрещен'
string_409 = 'Конфликт'
string_400 = 'Некорректный запрос'
string_404 = 'Не найдено'
string_401 = 'Не авторизован'
string_400_already_authed = 'Уже авторизован'

string_orgs_inn_not_unique = 'ИНН уже используется'
string_orgs_org_not_found = 'Запрашиваемая организация не найдена'
string_orgs_org_not_active = 'Организация не активна'
string_orgs_member_not_found = 'Участник не найден'
string_orgs_member_status_already_set = 'Указан уже установленный статус участника'

string_inv_wrong_expires = 'Указана неверная дата истечения срока действия приглашения'
string_inv_max_invitations = 'Достигнут предел количества активных приглашений'
string_inv_expired = 'Срок действия приглашения истек'
string_inv_not_found = 'Приглашение не найдено'
string_inv_max_usages = 'Приглашение использовано максимальное кол-во раз'
string_inv_owner_error = 'Вы являетесь владельцем этой организации'
string_inv_already_member = 'Вы уже являетесь участником этой организации'
string_inv_blocked_member = 'Вы были заблокированы владельцем организации'

string_storage_max_size = 'Файл слишком большой'
string_storage_wrong_filetype = 'Неверный формат файла'
string_storage_empty_filename = 'Имя файла не указано'
string_storage_saving_error_db = 'Ошибка при информации о файле'

string_user_email_exist = 'Указанный адрес электронной почты уже используется'
string_user_username_exist = 'Указанный логин уже используется'
string_user_telnum_exist = 'Указанный номер телефона уже используется'
string_user_telegram_exist = 'Указанный тег Telegram уже используется'
string_user_register_error = 'Ошибка сервера при регистрации пользователя. Обновите страницу и повторите попытку'
string_user_wrong_password = 'Неверный пароль или имя пользователя'
string_user_inactive_user = 'Учетная запись не активна'

string_product_parsing_error = 'Ошибка при парсинге карточки товара Wildberries'
string_product_parsing_url_error = 'Невозможно определить артикул товара. Проверьте правильность ссылки'
string_product_products_response_error = 'Ошибка получения данных от Wildberries'
string_product_products_response_empty = 'Товары по артикулу не найдены'
string_products_product_not_found = 'Товар не найден'

string_product_size_not_in_stock = 'Размер товара не в наличии'
string_product_product_not_in_stock = 'Товар не в наличии'
string_product_multiple_sizes_error = 'Укажите размер товара (товар имеет несколько размеров)'
string_product_size_not_found = 'Товар не найден'
string_product_size_not_selected_but_match = 'Размер не указан'
string_product_too_many_files = 'Максимальное количество файлов 5'

string_orders_time_error = 'Задачи на текущие сутки регистрируются до 9:00. Пожалуйста, выберите один из следующих дней'
string_orders_max_amount = 'Максимальное количество должно быть не более 500'
