string_500 = 'Произошла ошибка при выполнении операции. Обновите страницу и повторите попытку'
string_200 = 'Операция успешно выполнена'
string_403 = 'Доступ запрещен'
string_409 = 'Конфликт'
string_400 = 'Некорректный запрос'
string_404 = 'Не найдено'

string_orgs_inn_not_unique = 'ИНН уже используется'
string_orgs_org_not_found = 'Запрашиваемая организация не найдена'

string_inv_expired = 'Срок действия приглашения истек'
string_inv_not_found = 'Приглашение не найдено'
string_inv_max_usages = 'Приглашение использовано максимальное кол-во раз'
string_inv_owner_error = 'Вы являетесь владельцем этой организации'
string_inv_alredy_member = 'Вы уже являетесь участником этой организации'
string_inv_blocked_member = 'Вы были заблокированы владельцем организации'

string_storage_max_size = 'Файл слишком большой'
string_storage_wrong_filetype = 'Неверный формат файла'
string_storage_empty_filename = 'Имя файла не указано'
